### PR TITLE
Add AppShell to skeleton starter CDI and remove PWA from MainView

### PR DESCRIPTION
**Pull request by shadikhani**
Fix https://github.com/vaadin/skeleton-starter-flow-cdi/issues/177

This change is [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-cdi/178)

### CODE REVIEW

**Comment by anasmi** [comment]
___
*[src/main/java/org/vaadin/example/AppShell.java, line 10 at r3](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-cdi/178#-M5LII8hCJShUFa7UDas:-M5LII8hCJShUFa7UDat:b-t4vv54) ([raw file](https://github.com/vaadin/skeleton-starter-flow-cdi/blob/67df7cf4d0cdf4debf7f9bbeb00c16bcef26f579/src/main/java/org/vaadin/example/AppShell.java#L10)):*
> ```Java
>  * and some desktop browsers.
>  */
> @PWA(name = "Project Base for Vaadin with Spring", shortName = "Project Base")
> ```

`with Spring` should be removed. This is a CDI project

**Comment by shadikhani** [comment]
> _[src/main/java/org/vaadin/example/AppShell.java, line 10 at r3](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-cdi/178#-M5LII8hCJShUFa7UDas:-M5LII8hCJShUFa7UDat:b-t4vv54) ([raw file](https://github.com/vaadin/skeleton-starter-flow-cdi/blob/67df7cf4d0cdf4debf7f9bbeb00c16bcef26f579/src/main/java/org/vaadin/example/AppShell.java#L10)):_
> 
> > ```java
> >  * and some desktop browsers.
> >  */
> > @PWA(name = "Project Base for Vaadin with Spring", shortName = "Project Base")
> > ```
> 
> `with Spring` should be removed. This is a CDI project

Done

**Comment by shadikhani** [comment]
> > _[Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-cdi/178)_ status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @shadikhani)
> 
> _[src/main/java/org/vaadin/example/MainView.java, line 11 at r1](https://reviewable.io/reviews/vaadin/skeleton-starter-flow-cdi/178#-M2rlCxOC6R2JoKERcj_:-M2rlCxP856yPHaxLZ3P:b-pgxvpz) ([raw file](https://github.com/vaadin/skeleton-starter-flow-cdi/blob/c138ca98aaaa4fcfd1c6dc4827ce519b56b4f619/src/main/java/org/vaadin/example/MainView.java#L11)):_
> 
> > ```java
> > import com.vaadin.flow.component.textfield.TextField;
> > import com.vaadin.flow.router.Route;
> > import com.vaadin.flow.server.PWA;
> > ```
> 
> remove the unused import

Done

**Comment by anasmi** [comment]
@tmattsso could you check this? :)

**Pull request merged**
